CTSt=input("Enter CTSt:")
CTSr=input("Enter CTSr:")
CTCt=input("Enter CTCt:")
CTCr=input("Enter CTCr:")
CTSt=float(CTSt)
CTSr=float(CTSr)
CTCt=float(CTCt)
CTCr=float(CTCr)
FOLD_CHANGE=2**-(CTSt-CTSr)/2**-(CTCt-CTCr)
print("FOLD_CHANGE is", FOLD_CHANGE)
